language: scala

jdk:
  - oraclejdk8

scala:
  - 2.11.11

before_install:
  - wget https://downloads.lightbend.com/scala/2.11.12/scala-2.11.12.tgz
  - tar xzf scala-2.11.12.tgz
  - PATH=${PATH}:scala-2.11.12/bin

script:
  - scala -version
  - ./gradlew buildDependents
  - bash bin/test.sh &> test.log
  - grep -B12 'Unexpected exit code' test.log
  - grep ^diff test.log | sed -e 's/diff \(.*\) \(.*\)/echo diff \1 \2; diff -u \1 \2/' | sh
  - javap ./modbat-test/build/classes/scala/main/modbat/test/GenLabel3
