language: scala
scala:
   - 2.11.11
script: which scala && echo $SCALA_HOME && exit 1 && ./gradlew buildDependents && ls -lR && (bash bin/test.sh; find . -name '*.log' -o -name '*.err' | sed -e 's/\(.*\)/echo \1; cat \1/' | sh)
