dist: xenial

language: scala

addons:
  apt:
    packages:
      - oracle-java8-installer
      - scala

jdk:
  - oraclejdk8

scala:
  - 2.11.11

script:
  - scala -version
  - ./gradlew buildDependents
  - bash bin/test.sh
  - find . -name '*.log' -o -name '*.err' | sed -e 's/\(.*\)/echo \1; cat \1/' | sh
